CREATE TABLE `basicQuiz`(
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `count` INT(11) NOT NULL,
  `paperId` INT(11) NOT NULL ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;